[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0gfile:///home/dom/Downloads/Big%20Hero%206%20(2014)%20[1080p]/Big.Hero.6.2014.1080p.BluRay.x264.YIFY.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\xe\xff\0\0\x4%\0\0\a\x80\0\0\0\0\0\0\xe\xff\0\0\x4%\0\0\0\x1\0\0\0\0\a\x80\0\0\a\x80\0\0\0\0\0\0\xe\xff\0\0\x4%)

[FullScreen]
pos=@Point(2480 1016)
screen=@Rect(1920 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1920 991)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/dom/Downloads/Big%20Hero%206%20(2014)%20[1080p]/Big.Hero.6.2014.1080p.BluRay.x264.YIFY.mp4
times=0
