[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xa8\x66ile:///home/dom/Downloads/Anchorman%20The%20Legend%20Of%20Ron%20Burgundy%20(2004)%20[1080p]/Anchorman.The.Legend.Of.Ron.Burgundy.2004.1080p.BrRip.x264.BOKUTOX.YIFY.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x10\0\0\a\x7f\0\0\x4\x37\0\0\0\x1\0\0\0\x11\0\0\a~\0\0\x4\x36\0\0\0\0\0\0\0\0\a\x80\0\0\0\x1\0\0\0\x11\0\0\a~\0\0\x4\x36)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1918 991)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/dom/Downloads/Anchorman%20The%20Legend%20Of%20Ron%20Burgundy%20(2004)%20[1080p]/Anchorman.The.Legend.Of.Ron.Burgundy.2004.1080p.BrRip.x264.BOKUTOX.YIFY.mp4, file:///home/dom/grolps/movies/parasite/Parasite.mkv, file:///home/dom/grolps/shows/spongebob/season-1/SpongeBob%20SquarePants%20S01%20(360p%20re-dvdrip)/SpongeBob%20SquarePants%20S01E01a%20Help%20Wanted.mp4, file:///home/dom/grolps/shows/succession/season-1/Succession%20S01E01.mp4, file:///home/dom/grolps/shows/succession/season-1/Succession%20S01E10.mp4, file:///home/dom/Downloads/Big%20Hero%206%20(2014)%20[1080p]/Big.Hero.6.2014.1080p.BluRay.x264.YIFY.mp4
times=1325650, 5869014, 130150, 0, 0, 0
